<getBooksForUsersResponse>
    <user>
        <id>${id}</id>
        <lastname>${lastName}</lastname>
        <firstname>${firstName}</firstname>
        <streetname>$streetName}</streetname>
        <housenumber>${houseNumber}</housenumber>
        <postalcode>${postalCode}</postalcode>
        <city>${city}</city>
        <books>
            <#list books as book>
            <book>
                <id>${book.id}</id>
                <title>${book.title}</title>
                <author>${book.author}</author>
                <year>${book.year}</year>
            </book>
            </#list>
        </books>
    </user>
</getBooksForUsersResponse>